name = "sveltia-cms-auth"
main = "src/index.js"
compatibility_date = "2023-03-24"

# Keep variables/secrets configured in the Cloudflare Dashboard when deploying
# through Wrangler or a connected CI/CD pipeline.
keep_vars = true

[vars]
ALLOWED_DOMAINS = "firefly.ssyin033.top"
GITHUB_CLIENT_ID = "Ov23lirlEXeb3yD22scN"
